src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CalendarRepository::class)]
class Calendar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $heure = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;


/* 
    #[ORM\ManyToOne(inversedBy: 'calendars')]
    private ?Useretudiant $etudiant = null; */

    #[ORM\ManyToOne(inversedBy: 'calendars')]
    private ?Userentreprise $entreprise = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name:"candidature_id", referencedColumnName:"id", onDelete:"SET NULL")]

    private ?Candidature $Condidature = null;


    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeure(): ?int
    {
        return $this->heure;
    }

    public function setHeure(int $heure): static
    {
        $this->heure = $heure;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

public function getEntreprise(): ?Userentreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Userentreprise $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getCondidature(): ?Candidature
    {
        return $this->Condidature;
    }

    public function setCondidature(?Candidature $Condidature): static
    {
        $this->Condidature = $Condidature;

        return $this;
    }

 

 
}

src/Controller/InterviewController.php
<?php

namespace App\Controller;

use App\Entity\Calendar;
use App\Entity\Candidature;
use App\Form\InterviewForm;
use App\Form\InterviewType;
use App\Form\OffreFormType;
use App\Repository\CalendaractivityRepository;
use App\Repository\CalendarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Form\CalendarType;
use Psr\Log\LoggerInterface;
use App\Entity\Userentreprise;

use App\Repository\CandidatureRepository;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Notifier\Event\NotificationEvents;
use Symfony\Component\Notifier\Notification\PushNotificationInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class InterviewController extends AbstractController
{
    private $mailer;
    
    

    public function __construct(MailerInterface $mailer)
    {
        $this->mailer = $mailer;
       
    }
#[Route('/showcalender', name: 'show_interiew')]
    public function index(CalendarRepository $calendarRepository, SessionInterface $session): Response
    {
        $user = $session->get('user');
    
        if (!$user) {
            // Rediriger vers la page de connexion si l'utilisateur n'est pas connecté
            return $this->redirectToRoute('app_login');
        }

       
        $events = $calendarRepository->findBy(['entreprise' => $user->getId()]);

        $rdvs = [];
    
        foreach ($events as $event) {
            $rdvs[] = [
                'id' => $event->getId(),
                'date' => $event->getDate()->format('Y-m-d H:i:s'),
                'heure' => $event->getHeure(),
            ];
        }
    
        $data = json_encode($rdvs);
        return $this->render('interview/calender.html.twig', ['data' => $data]);

    }

   

    #[Route('/listevent', name: 'list_interview')]
    public function listBook(CalendarRepository $calendar, SessionInterface $session): Response
    {
        // Récupérer l'utilisateur depuis la session
        $user = $session->get('user');
    
        if (!$user) {
            // Rediriger vers la page de connexion si l'utilisateur n'est pas connecté
            return $this->redirectToRoute('app_login');
        }
    
        // Récupérer la liste des offres associées à l'entreprise de l'utilisateur
        $filteredOffres = $calendar->findBy(['entreprise' => $user->getId()]);
    
        return $this->render('interview/show.html.twig', [
            'interview' => $filteredOffres,
        ]);
    }









    #[Route('/interview/edit/{id}', name: 'edit_interview', methods: ['GET', 'POST'])]
    public function editOffre(Request $request, ManagerRegistry $manager, $id, CalendarRepository $calendarRepository): Response
{
    $em = $manager->getManager();

    $calendar = $calendarRepository->find($id);

    if (!$calendar) {
        throw $this->createNotFoundException('interview not found');
    }

    $form = $this->createForm(CalendarType::class, $calendar);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $em->persist($calendar);
        $em->flush();
        $this->sendEmail($calendar);

        return $this->redirectToRoute('list_interview', ['message' => 'Interview updated successfully'], Response::HTTP_SEE_OTHER);
    }

    return $this->render('interview/edit.html.twig', [
        'calendar' => $calendar,
        'form' => $form,
    ]);
} 


/* public function edit(Request $request, Calendar $calendar, CalendarRepository $calendarRepository): Response
{
    $form = $this->createForm(CalendarType::class, $calendar);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $calendarRepository->save($calendar);

        $this->addFlash('success', 'Calendar updated successfully.');
        return $this->redirectToRoute('list_interview');
    }

    return $this->render('interview/edit.html.twig', [
        'calendar' => $calendar,
        'form' => $form->createView(),
    ]);
} */


    
    
    #[Route('/addevent', name: 'add_interiew')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
{


        $candidature = $entityManager->getRepository(Candidature::class)->find(1);

        
     $calendar = new Calendar();
        $calendar->setCondidature($candidature);

        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            // Handle form submission
            $entityManager->persist($calendar);
            $entityManager->flush();
    
            return $this->redirectToRoute('list_interview', ['message' => 'Interview Added successfully'], Response::HTTP_SEE_OTHER);
        }
    
        return $this->render('interview/addinterview.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/addevent/{candidature}', name: 'add_interie')]
public function new1(Request $request, EntityManagerInterface $entityManager, Candidature $candidature,SessionInterface $session): Response
{
    // No need to fetch $candidature again, it's already injected by Symfony
   


    $user = $session->get('user');
    if (!$user) {
        // Rediriger vers la page de connexion si l'utilisateur n'est pas connecté
        return $this->redirectToRoute('app_login');
    }
    // Assuming Entreprise is associated with Offre, adjust this based on your entity relationships
    $entreprise = $entityManager->getRepository(Userentreprise::class)->find($user->getId());
    
    $calendar = new Calendar();
    $calendar->setCondidature($candidature);
    $calendar->setEntreprise($entreprise);

    $form = $this->createForm(CalendarType::class, $calendar);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        // Handle form submission
        $entityManager->persist($calendar);
        $entityManager->flush();
        $this->sendEmail($calendar);

        // Mark the candidature as treated
        $candidature->setIsTreated(true);
        
        // Persist and flush the candidature to save the changes
        $entityManager->persist($candidature);
        $entityManager->flush();

        return $this->redirectToRoute('list_interview', ['message' => 'Interview Added successfully'], Response::HTTP_SEE_OTHER);
    }

    return $this->render('interview/addinterview.html.twig', [
        'form' => $form->createView(),
        'candidature' => $candidature,
    ]);


} 
    
    





    #[Route('/interview/delete/{id}', name: 'interview_delete')]
public function deleteBook(Request $request, $id, ManagerRegistry $manager, CalendarRepository $offreRepository): Response
{
    $em = $manager->getManager();
    $book = $offreRepository->find($id);

    $em->remove($book);
    $em->flush();

    return $this->redirectToRoute('list_interview', ['message' => 'Interview Deleted successfully'], Response::HTTP_SEE_OTHER);
}


private function sendEmail(Calendar $calendar): void
{
    // Accédez aux entités liées pour obtenir l'adresse e-mail
    $etudiantEmail = $calendar->getCondidature()->getEtudiant()->getEmail();

    // Vérifiez si l'adresse e-mail est définie
    if ($etudiantEmail) {
        // Créez les données à passer au template Twig
        $emailData = [
            'calendar' => $calendar,
            // Ajoutez d'autres données que vous souhaitez passer au modèle ici
        ];

        // Créez le corps HTML de l'e-mail
        $emailBody = $this->renderView('interview/mail.html.twig', $emailData);

        // Créez l'e-mail avec le corps HTML
        $email = (new Email())
            ->from('test.pidev123@gmail.com')
            ->to($etudiantEmail)
            ->subject('Confirmation d\'entretien')
            ->html($emailBody);

        $this->mailer->send($email);
    }
}





}

templates/interview/add.html.twig
    <div class="modal" id="eventModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Ajouter un Entretien</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                        {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.etudiant, 'Nom du Candidat :') }}
                            {{ form_widget(form.etudiant, {'attr': {'class': 'form-control', 'id': 'eventNom'}}) }}
                            {{ form_errors(form.etudiant) }}
                        </div>

                        <div class="form-group">
                            {{ form_label(form.date, 'Date de l\'Entretien  :') }}
                            {{ form_widget(form.date, {'attr': {'class': 'form-control', 'id': 'eventDate', name: 'eventDate'}}) }}
                        </div>

                        <div class="form-group">
                            {{ form_label(form.heure, 'Heure de l\'Entretien :') }}
                            {{ form_widget(form.heure, {'attr': {'class': 'form-control', 'id': 'eventHeure'}}) }}
                            {{ form_errors(form.heure) }}
                        </div>

                        <button type="submit" class="btn btn-primary">Ajouter un Entretien</button>
                        {{ form_end(form) }}
                 
                </div>
            </div>
        </div>
    </div>

templates/interview/addinterview.html.twig
{% extends 'baseE.html.twig' %}
{% block div %}
    <h3>Ajouter Un interview</h3>
{% endblock %}
{% block body %}
<section class="section-padding section-bg">
    <div class="container">
    
<form method="POST" action="{{ path('add_interie', { 'candidature': candidature.id }) }}" enctype="multipart/form-data">

    {{ form_start(form) }}
  
    
              
              

    <div class="col-lg-6 col-md-6 col-12 mb-3 form-floating">
    {{ form_widget(form.heure, {'attr': {'class': 'form-control', 'placeholder': 'Fonction', 'required': 'required'}}) }}
    <label for="{{ form.heure.vars.id }}">heure</label>
    {{ form_errors(form.heure) }}
</div>

<div class="col-lg-6 col-md-6 col-12 mb-3 form-floating">
    {{ form_widget(form.date, {'attr': {'class': 'form-control datepicker', 'placeholder': 'Date ', 'required': 'required'}}) }}
    <label for="{{ form.date.vars.id }}">Date de l'interview</label>
    {{ form_errors(form.date) }}
</div>



              

                <div class="col-lg-12 col-md-12 col-12">
                    <button type="submit" class="btn btn-primary">Add Interview</button>
                </div>
            </div>
            {{ form_end(form) }}
            
        </form>
    </div>
</section>
{% endblock %}

templates/interview/calender.html.twig
{% extends 'baseE.html.twig' %}
{% block body %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="ons/fonts/icomoon/style.css">

    <link href='ons/fullcalendar/packages/core/main.css' rel='stylesheet' />
    <link href='ons/fullcalendar/packages/interaction/main.css' rel='stylesheet' />
    <link href='ons/fullcalendar/packages/daygrid/main.css' rel='stylesheet' />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="ons/css/bootstrap.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="ons/css/style.css">

    <title>Calendrier #9</title>
</head>
<body>

<div class="content">
    <div id='calendar'></div>
</div>



<script src="ons/js/jquery-3.3.1.min.js"></script>
<script src="ons/js/popper.min.js"></script>
<script src="ons/js/bootstrap.min.js"></script>

<script src='ons/fullcalendar/packages/core/main.js'></script>
<script src='ons/fullcalendar/packages/interaction/main.js'></script>
<script src='ons/fullcalendar/packages/daygrid/main.js'></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
            plugins: [ 'interaction', 'dayGrid' ],
            defaultDate: '2020-02-12',
            editable: true,
            eventLimit: true, // allow "more" link when too many events,
            selectable: true, // enable user to select dates
            events: {{ data|raw }},
              dateClick: function(info) {
                var dateStr = info.dateStr;
                $('#eventDate').val(dateStr); // Set the selected date in the form
                $('#eventModal').modal('show'); // Show the modal
            }
           
        });


        calendar.render();
    });
</script>

<script src="ons/js/main.js"></script>
</body>
</html>
{% endblock %}

templates/interview/edit.html.twig
{% extends 'baseE.html.twig' %}
{% block div %}
    <h3>Edit  interview</h3>
{% endblock %}
{% block body %}
<section class="section-padding section-bg">
    <div class="container">
<form method="post" action="{{ path('edit_interview', {'id': calendar.id}) }}">

{{ form_start(form) }}
            <div class="row">
 


</div>      

    <div class="col-lg-6 col-md-6 col-12 mb-3 form-floating">
    {{ form_widget(form.heure, {'attr': {'class': 'form-control', 'placeholder': 'Fonction', 'required': 'required'}}) }}
    <label for="{{ form.heure.vars.id }}">heure</label>
    {{ form_errors(form.heure) }}
</div>

<div class="col-lg-6 col-md-6 col-12 mb-3 form-floating">
    {{ form_widget(form.date, {'attr': {'class': 'form-control datepicker', 'placeholder': 'Date ', 'required': 'required'}}) }}
    <label for="{{ form.date.vars.id }}">Date de l'interview</label>
    {{ form_errors(form.date) }}
</div>
<div class="col-lg-12 col-md-12 col-12">
                    <button type="submit" class="btn btn-primary">Edit Offre</button>
                </div>


              

            {{ form_end(form) }}
            
        </form>
    </div>
</section>
{% endblock %}

templates/interview/mail.html.twig
{# interview/mail.html.twig #}

<!DOCTYPE html>
<html>
<head>
    <title>Interview Confirmation</title>
</head>
<body>
    <h1>Interview Confirmation</h1>

    {# Accessing properties of the Calendar object passed to the template #}
    <p>
        Dear {{ calendar.condidature.etudiant.firstName }} {{ calendar.condidature.etudiant.lastName }},
    </p>

    <p>You are invited for an interview at our company. Here are the details of the interview:</p>

    <dl>
        <dt>Interview date:</dt>
        <dd>{{ calendar.date|date('Y-m-d') }}</dd>

        <dt>Interview heure:</dt>
        <dd>{{ calendar.heure }}</dd>
    </dl>

    <p>         

        We are waiting for you!
    </p>
</body>
</html>

templates/interview/show.html.twig
{% extends 'baseE.html.twig' %}
{% block div %}
    <h3>La liste des Interviews</h3>
{% endblock %}
{% block body %}
    {% block first_content %}
        <div align="center" style="margin-top: 20px;">
            <style>
                table {
                    border-collapse: collapse;
                    width: 80%;
                }

                th, td {
                    border: 1px solid #ddd;
                    padding: 8px;
                    text-align: left;
                }
            </style>
            <table align="center">
                <thead>
                    <tr>
                        <th>Heure</th>
                        <th>Date</th>
                         <th>etudiant UserName</th>

                                    <th>etudiant Email</th>

                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in interview %}
                        <tr>

                            <td>{{ i.heure }}</td>
                            <td>{{ i.Date ? i.Date|date('Y-m-d') : '' }}</td>

                        <td>{{ i.Condidature.etudiant.username | default('N/A')  }}</td>
                          <td>{{ i.Condidature.etudiant.email | default('N/A') }}</td>
                            <td>
                                <a href="{{ path('edit_interview', { id: i.id }) }}">Edit</a>
                                <a href="{{ path('interview_delete', { id: i.id }) }}">Delete</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="3">Aucune interview trouvée.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endblock %}
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        if (!('Notification' in window)) {
            console.log('This browser does not support desktop notifications.');
            return;
        }

        if (Notification.permission === 'granted') {
            showNotification();
        } else if (Notification.permission !== 'denied') {
            Notification.requestPermission().then(function(permission) {
                if (permission === 'granted') {
                    showNotification();
                }
            });
        }
    });

    function showNotification() {
        var urlParams = new URLSearchParams(window.location.search);
        var message = urlParams.get('message');

        if (message) {
            var notification = new Notification(message);

            notification.addEventListener('click', function() {
                window.location.href = '{{ path("list_interview") }}';
            });
        }
    }
</script>
{% endblock %}